version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api 
    volumes:
      - ./api:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: defaultdb
      DB_USERNAME: root
      DB_PASSWORD: root
      QUEUE_CONNECTION: redis
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: 

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./api:/app
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  frontend:
    build:
      context: 
      dockerfile: Dockerfile.fe.dev
    container_name: frontend
    ports:
      - 8080:8080
    volumes: 
      - ./fe:/app
    stdin_open: true
    tty: true
    environment: 
      HOST: 0.0.0.0
      VUE_APP_API_BASE_URL: http://127.0.0.1:8000/api
      CHOKIDAR_USEPOLLING: 'true'
    depends_on: 
      - nginx
      - api

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=defaultdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    volumes:
      - ./api/storage/mysql:/var/lib/mysql
    ports:
      - 33060:3306

  redis:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - ./api/storage/redis:/data
    ports:
      - 63790:6379
