version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api 
    volumes:
      - ./:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: 
      DB_USERNAME: root
      DB_PASSWORD: root
      QUEUE_CONNECTION: redis
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: 

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  frontend:
    build:
      context: 
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 8080:8080
    volumes: 
      - ./doer-fe:/app
    stdin_open: true
    tty: true
    environment: 
      HOST: 0.0.0.0
      VUE_APP_API_BASE_URL: http://127.0.0.1:8000/api
      CHOKIDAR_USEPOLLING: 'true'
    depends_on: 
      - nginx
      - api

